# Generated by Django 5.0.3 on 2024-05-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.CharField(max_length=250, verbose_name='Предмет')),
                ('lesson_type', models.CharField(max_length=250, verbose_name='Категория')),
            ],
        ),
    ]
