# Generated by Django 5.0.3 on 2024-05-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=250, verbose_name='Класс')),
                ('group_type', models.CharField(max_length=250, verbose_name='Тип')),
                ('group_number', models.IntegerField(verbose_name='Номер')),
            ],
        ),
    ]
