# Generated by Django 5.0.3 on 2024-05-20 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='student',
        ),
        migrations.AddField(
            model_name='check',
            name='student',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.student'),
        ),
    ]
