# Generated by Django 5.0.3 on 2024-05-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='checks',
            field=models.BooleanField(default=True, verbose_name='Был'),
        ),
    ]
