# Generated by Django 5.0.3 on 2024-05-20 20:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_mark_checks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpId', models.IntegerField(verbose_name='EmpId')),
                ('Name', models.CharField(max_length=50, verbose_name='Name')),
                ('Site', models.CharField(max_length=50, verbose_name='Site')),
                ('Days', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Days')),
                ('Nh', models.IntegerField(verbose_name='Nh')),
                ('SingleOt', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='SingleOt')),
                ('DoubleOt', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='DobleOt')),
                ('Status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('O', 'Off')], max_length=10, verbose_name='Status')),
                ('AttendenceOn', models.DateField(default=datetime.datetime(2024, 5, 20, 23, 12, 35, 744696))),
            ],
        ),
    ]
