# Generated by Django 5.0.3 on 2024-05-20 20:19

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_attendence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendence',
            name='Days',
        ),
        migrations.RemoveField(
            model_name='attendence',
            name='DoubleOt',
        ),
        migrations.RemoveField(
            model_name='attendence',
            name='Nh',
        ),
        migrations.RemoveField(
            model_name='attendence',
            name='SingleOt',
        ),
        migrations.RemoveField(
            model_name='attendence',
            name='Site',
        ),
        migrations.AddField(
            model_name='attendence',
            name='group',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.group'),
        ),
        migrations.AddField(
            model_name='attendence',
            name='lesson',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.lesson'),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='AttendenceOn',
            field=models.DateField(default=datetime.datetime(2024, 5, 20, 23, 19, 37, 964501)),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='Name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.student', verbose_name='Name'),
        ),
    ]
